### ISSUE TITLE
Fix Join Ride Functionality

### ISSUE THREAD

**Issue by Abhi0010** [KoruptTinker/PackTravel#5]
Join Ride Functionality not working
![Capture](https://github.com/user-attachments/assets/cae44437-8feb-45f6-9d53-68604064ae4d)

**Comment by KoruptTinker** [comment]
This feature needs to be built from the ground up.
The button is just there on the FE. No calls are going to the BE for this

**Comment by KoruptTinker** [comment]
Identified the issue. API Call is missing id parameter of the route. 
Reason: Not being rendered properly from the BE

**Comment by KoruptTinker** [comment]
Raised #6 as a fix for this
